### ISSUE TITLE
Facepunch_Connector_Cancelled

### ISSUE THREAD

**Issue by xbelanch** [d3adwolf/rustlegacy#5] opened 2022-03-14 18:49 UTC
This is an old known "bug" but the weird point is to know why is happen for some ppl (and no others). Let me explain: I have no issues to connect and enter into a local rust legacy server but not for a mate of mine. He always get:

![rust_nIaOJSYndI](https://user-images.githubusercontent.com/23429/158240108-780c4a27-62ce-4d2a-bf39-850d67b5a598.png)

I googled a solution without no success. Any clue or workaround?

**Comment by d3adwolf** [comment] 2022-05-23 19:13
Forgive me for replying months later:
- Have a friend check the .NET 3.5 Framework and VS C++ Redistributable for availability and relevance
- Maybe it's the shenanigans of the pirate DLL files, which just let us play with each other right now
- Maybe an error appears when connecting to local network (192.168.1.*)
- You can try to run the client Rust Buster and log in through it - they fixed a lot of bugs

**Comment by d3adwolf** [comment] 2022-05-23 19:14
I'll close the issue because it's not really related to my repository, but I'd love it if you'd write back later and tell me what progress you're making with your friend.

**Comment by d3adwolf** [comment] 2022-06-20 18:01
> This is an old known "bug" but the weird point is to know why is happen for some ppl (and no others). Let me explain: I have no issues to connect and enter into a local rust legacy server but not for a mate of mine. He always get:
> 
> ![rust_nIaOJSYndI](https://user-images.githubusercontent.com/23429/158240108-780c4a27-62ce-4d2a-bf39-850d67b5a598.png)
> 
> I googled a solution without no success. Any clue or workaround?

Look at issue #1, there will be a solution to your problem.

**Comment by d3adwolf** [comment] 2022-06-20 18:02
And so it is not a bug, but an error, reporting that the connection has been reset by the server.

**Closed as completed by d3adwolf** 2022-06-20 18:01 UTC
